# fly.toml app configuration file generated for wedding-season on 2023-12-21T09:51:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wedding-season"
primary_region = "ewr"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "poetry run python manage.py migrate"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "weddingseason.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
