# Generated by Django 5.0 on 2023-12-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RD', 'Rehearsal Dinner'), ('RE', 'Reception'), ('WC', 'Wedding Ceremony')], max_length=2)),
                ('description', models.TextField(max_length=250)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wedding')),
            ],
            options={
                'ordering': ['start_date_time'],
            },
        ),
    ]
