# Generated by Django 5.0 on 2023-12-19 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='Start Date and Time'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('B', 'Bride'), ('G', 'Groom'), ('P', 'Planner')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wedding')),
            ],
        ),
    ]
