# Generated by Django 5.0 on 2023-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_profile_type_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('B', 'Bride'), ('G', 'Groom'), ('P', 'Planner')], max_length=1, verbose_name='Wedding Role'),
        ),
    ]
