# Generated by Django 5.0 on 2023-12-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rsvp_choice', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('dietary_restrictions', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
