# Generated by Django 5.0 on 2023-12-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp_choice',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
