# Generated by Django 5.0 on 2023-12-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_guest_rsvp_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='wedding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.wedding'),
            preserve_default=False,
        ),
    ]
