# Generated by Django 5.0 on 2023-12-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_guest_wedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(to='main_app.guest'),
        ),
    ]
