# Generated by Django 5.0 on 2023-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('BC', 'Bachelor Party'), ('BT', 'Bachelorette Party'), ('BS', 'Bridal Shower'), ('RE', 'Reception'), ('RD', 'Rehearsal Dinner'), ('WB', 'Wedding Brunch'), ('WC', 'Wedding Ceremony')], max_length=2),
        ),
    ]
